install.packages("lme4")
install.packages("lmerTest")
library("lmerTest")
library(lme4)

behav <- read.csv("for_r_1.csv", header=TRUE, sep=",")
behav <- subset(behav, sol <= 6500)
behav <- subset(behav, rep=="ok")
behav <- subset(behav, type != "NA")
nrow(behav)

#condition x voice
nrow(subset(behav, behav$cond=="A"&behav$type=="act"))
nrow(subset(behav, behav$cond=="A"&behav$type=="pass"))
nrow(subset(behav, behav$cond=="none"&behav$type=="act"))
nrow(subset(behav, behav$cond=="none"&behav$type=="pass"))
nrow(subset(behav, behav$cond=="P"&behav$type=="act"))
nrow(subset(behav, behav$cond=="P"&behav$type=="pass"))

#average
mean(behav$sol)
sd(behav$sol)
2*(sd(behav$sol)/sqrt(nrow(behav)))

#all actives and all passives
behav$type <- ifelse(behav$type=="act", 1,0)
behav$cond <- as.factor(behav$cond)
mod1 <- lmer(log(sol) ~ type + (1+type|item) + (1+type|ppt.no), behav)
summary(mod1)
act <- subset(behav, type=="act")
mean(act$sol)
sd(act$sol)
pass <- subset(behav, type=="pass")
mean(pass$sol)
sd(pass$sol)
nrow(act)
2*(sd(apv$sol)/sqrt(nrow(apv)))
nrow(pass)
2*(sd(pass$sol)/sqrt(nrow(pass)))

#topicalized and non-topicalized APV actives
apv <- subset(behav, type=="act"&wo =="APV"& (cond=="A"|cond=="none"))
apv$top <- ifelse(apv$cond=="A", 1,0)
mod2 <- lmer(log(sol) ~ top + (1+top|item) + (1+top|ppt.no), apv)
summary(mod2)
apv_a <- subset(apv, cond=="A")
mean(apv_a$sol)
sd(apv_a$sol)
apv_n <- subset(apv, cond=="none")
mean(apv_n$sol)
sd(apv_n$sol)
nrow(apv_n)
2*(sd(apv_n$sol)/sqrt(nrow(apv_n)))
nrow(apv_a)
2*(sd(apv_a$sol)/sqrt(nrow(apv_a)))

#propropped and non-prodropped actives
act_pd <- subset(behav, cond=="A"& type =="act"& (wo=="APV"|wo=="PV"))
nrow(act_pd)
act_pd$pd <- ifelse(act_pd$wo=="APV", 1,0)
mod3 <- lmer(log(sol) ~ pd + (1+pd|item) + (1+pd|ppt.no), act_pd)
summary(mod3)
act_apv <- subset(act_pd, wo=="APV")
mean(act_apv$sol)
sd(act_apv$sol)
act_pv <- subset(act_pd, wo=="PV")
mean(act_pv$sol)
sd(act_pv$sol)
nrow(act_apv)
2*(sd(act_apv$sol)/sqrt(nrow(act_apv)))
nrow(act_pv)
2*(sd(act_pv$sol)/sqrt(nrow(act_pv)))

#propropped and non-prodropped passives
pass_pd <- subset(behav, cond=="P"& type =="pass"& (wo=="PAV"|wo=="AV"))
nrow(pass_pd)
pass_pd$pd <- ifelse(pass_pd$wo=="PAV", 1,0)
mod4 <- lmer(log(sol) ~ pd + (1+pd|item) + (1+pd|ppt.no), pass_pd)
summary(mod4)
pass_pav <- subset(pass_pd, wo=="PAV")
mean(pass_pav$sol)
sd(pass_pav$sol)
pass_av <- subset(pass_pd, wo=="AV")
mean(pass_av$sol)
sd(pass_av$sol)
nrow(pass_pav)
nrow(pass_av)
2*(sd(pass_pav$sol)/sqrt(nrow(pass_pav)))
2*(sd(pass_av$sol)/sqrt(nrow(pass_av)))

#full actives and full passives 
full <- subset(behav, (cond=="none"& wo =="APV"& type=="act")|(cond=="P"&wo=="PAV"&type=="pass"))  
full$type <- ifelse(full$type=="act", 1,0)
mod5 <- lmer(log(sol) ~ type + (1+type|item) + (1+type|ppt.no), full)
summary(mod5)
full_act <- subset(full, type=="act")
mean(full_act$sol)
sd(full_act$sol)
full_pass <- subset(full, type=="pass")
mean(full_pass$sol)
sd(full_pass$sol)
nrow(full_act)
nrow(full_pass)
2*(sd(full_act$sol)/sqrt(nrow(full_act)))
2*(sd(full_pass$sol)/sqrt(nrow(full_pass)))
